package com.waes.diffservice.exception;

import com.waes.diffservice.ApplicationErrorEnum;
import lombok.Getter;
import lombok.Setter;

import java.text.MessageFormat;

/**
 * Implementation of the <a href="https://tools.ietf.org/html/rfc7807">RFC-7807</a>, a standard
 * for error response formats for HTTP APIs.
 */
@Getter
public abstract class GenericException extends RuntimeException {

    /**
     * A URI reference <a href="https://tools.ietf.org/html/rfc3986">RFC-3986</a> 6 that identifies the problem type.
     * This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type.
     * When this member is not present, its value is assumed to be "about:blank".
     */
    private final String type;

    /**
     * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
     * problem, except for purposes of localization.
     */
    private final String title;

    /**
     * The HTTP status code (<a href=" https://tools.ietf.org/html/rfc7231#section-6">RFC-7231, Section 6</a>)
     * generated by the origin server for this occurrence of the problem.
     */
    private final int status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    private final String detail;

    /**
     *  A URI reference that identifies the specific occurrence of the problem.
     *  It may or may not yield further information if dereferenced.
     */
    @Setter
    private String instance;

    protected GenericException(Throwable cause, ApplicationErrorEnum error, Object... args) {
        super(cause);

        this.type = error.getType();
        this.title = error.getTitle();
        this.status = error.getStatus();
        this.detail = MessageFormat.format(error.getDetail(), args);
    }

}
