---
swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
tags:
  - name: diff-controller
    description: Diff Controller
paths:
  "/v1/diff/{diffId}":
    get:
      tags:
        - diff-controller
      summary: Returns the differences between the registered Json's
      operationId: diffUsingGET
      produces:
        - application/json
      parameters:
        - name: diffId
          in: path
          description: The id of the diff
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Difference"
        '500':
          description: Internal Server Error
          schema:
            "$ref": "#/definitions/ErrorDTO"
  "/v1/diff/{diffId}/left":
    put:
      tags:
        - diff-controller
      summary: Saves the request body as the leftText of the given diff
      operationId: leftTextUsingPUT
      consumes:
        - text/plain
      produces:
        - "*/*"
      parameters:
        - name: diffId
          in: path
          description: diffId
          required: true
          type: integer
          format: int64
        - in: body
          name: leftText
          description: leftText
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/DiffData"
        '400':
          description: Bad Request. In this case the input is not a valid base64 string or it's not a valid Json Object
          schema:
            "$ref": "#/definitions/ErrorDTO"
        '500':
          description: Internal Server Error
          schema:
            "$ref": "#/definitions/ErrorDTO"
  "/v1/diff/{diffId}/right":
    put:
      tags:
        - diff-controller
      summary: Saves the request body as the leftText of the given diff
      operationId: rightTextUsingPUT
      consumes:
        - text/plain
      produces:
        - "*/*"
      parameters:
        - name: diffId
          in: path
          description: diffId
          required: true
          type: integer
          format: int64
        - in: body
          name: rightText
          description: rightText
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/DiffData"
        '400':
          description: Bad Request. In this case the input is not a valid base64 string or it's not a valid Json Object
          schema:
            "$ref": "#/definitions/ErrorDTO"
        '500':
          description: Internal Server Error
          schema:
            "$ref": "#/definitions/ErrorDTO"
definitions:
  DiffData:
    type: object
    properties:
      id:
        type: integer
        format: int64
      leftJson:
        type: string
      rightJson:
        type: string
    title: DiffData
  Difference:
    type: object
    properties:
      diffId:
        type: integer
        format: int64
      jsonDiff:
        "$ref": "#/definitions/JsonDiff"
      leftJson:
        type: string
      rigthJson:
        type: string
      stringDiff:
        "$ref": "#/definitions/StringDiff"
    title: Difference
  JsonDiff:
    type: object
    properties:
      equal:
        type: boolean
      jsonDifferences:
        type: array
        items:
          "$ref": "#/definitions/JsonDifference"
    title: JsonDiff
  JsonDifference:
    type: object
    properties:
      operation:
        type: string
      path:
        type: string
      value:
        type: string
    title: JsonDifference
  StringDiff:
    type: object
    properties:
      equal:
        type: boolean
      stringDifferences:
        type: array
        items:
          "$ref": "#/definitions/StringDifference"
    title: StringDiff
  StringDifference:
    type: object
    properties:
      length:
        type: integer
        format: int32
      offset:
        type: integer
        format: int32
    title: StringDifference
  ErrorDTO:
    title: ErrorDTO
    type: object
    properties:
      type:
        description: A URI reference that identifies the problem type.
        type: string
      title:
        description: A short, human-readable summary of the problem type.
        type: string
      status:
        description: The HTTP status code generated by the origin server for this occurrence of the problem.
        type: integer
        format: int32
      detail:
        description: A human-readable explanation specific to this occurrence of the problem.
        type: string
      instance:
        description: An unique identifier for the specific occurrence of the problem.
        type: string

